General:

    ListenAddress: 127.0.0.1
    ListenPort: 7450

    TLS:
        Enabled: true
        PrivateKey: ../../peerOrganizations/org5.example.com/orderers/orderer0.org5.example.com/tls/server.key
        Certificate: ../../peerOrganizations/org5.example.com/orderers/orderer0.org5.example.com/tls/server.crt
        RootCAs:
          - ../../peerOrganizations/org5.example.com/orderers/orderer0.org5.example.com/tls/ca.crt
        ClientAuthRequired: false
        ClientRootCAs:

    Keepalive:
        ServerMinInterval: 60s
        ServerInterval: 7200s
        ServerTimeout: 20s

    MaxRecvMsgSize: 104857600
    MaxSendMsgSize: 104857600

    Cluster:
        SendBufferSize: 10
        ClientCertificate:
        ClientPrivateKey:
        ListenPort:
        ListenAddress:
        ServerCertificate:
        ServerPrivateKey:

    BootstrapMethod: file
    BootstrapFile:

    LocalMSPDir: ../../peerOrganizations/org5.example.com/orderers/orderer0.org5.example.com/msp
    LocalMSPID: Org5MSP

    Profile:
        Enabled: false
        Address: 0.0.0.0:6460

    BCCSP:
        Default: SW

        SW:
            Hash: SHA2
            Security: 256
            FileKeyStore:
                KeyStore:

        PKCS11:
            Library:
            Label:
            Pin:
            Hash:
            Security:
            FileKeyStore:
                KeyStore:

    Authentication:
        TimeWindow: 15m

FileLedger:
    Location: /var/hyperledger/production/orderer

Kafka:

    Retry:
        ShortInterval: 5s
        ShortTotal: 10m
        LongInterval: 5m
        LongTotal: 12h
        NetworkTimeouts:
            DialTimeout: 10s
            ReadTimeout: 10s
            WriteTimeout: 10s
        Metadata:
            RetryBackoff: 250ms
            RetryMax: 3
        Producer:
            RetryBackoff: 100ms
            RetryMax: 3
        Consumer:
            RetryBackoff: 2s

    Topic:
        ReplicationFactor: 3
    Verbose: false

    TLS:
      Enabled: false
      PrivateKey:
      Certificate:
      RootCAs:
    SASLPlain:
      Enabled: false
      User:
      Password:
    Version:

Debug:
    BroadcastTraceDir:
    DeliverTraceDir:

Operations:
    ListenAddress: 127.0.0.1:8843
    TLS:
        Enabled: false
        Certificate:
        PrivateKey:
        ClientAuthRequired: false
        ClientRootCAs: []

Metrics:
    Provider: disabled
    Statsd:
      Network: udp
      Address: 127.0.0.1:8525
      WriteInterval: 30s
      Prefix:

Admin:
    ListenAddress: 127.0.0.1:9843
    TLS:
        Enabled: true
        Certificate: ../../peerOrganizations/org5.example.com/orderers/orderer0.org5.example.com/tls/server.crt
        PrivateKey: ../../peerOrganizations/org5.example.com/orderers/orderer0.org5.example.com/tls/server.key
        ClientAuthRequired: true
        ClientRootCAs: [../../peerOrganizations/org5.example.com/orderers/orderer0.org5.example.com/tls/ca.crt]

ChannelParticipation:
    Enabled: true
    MaxRequestBodySize: 1 MB

Consensus:
    WALDir: /var/hyperledger/production/orderer/etcdraft/wal
    SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot

# Change all addresses for different orderers
