version: '3.7'

networks:
  test:
    name: test

services:

  ca_org1:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    ports:
      - "7054:7054"
      - "17054:17054"
    command: sh -c 'fabric-ca-server start -b admin:admin1 -d'
    volumes:
      - ../organizations/fabric-ca/org1:/etc/hyperledger/fabric-ca-server
    container_name: ca_org1
    networks:
      - test

  ca_org2:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7154
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17154
    ports:
      - "7154:7154"
      - "17154:17154"
    command: sh -c 'fabric-ca-server start -b admin:admin2 -d'
    volumes:
      - ../organizations/fabric-ca/org2:/etc/hyperledger/fabric-ca-server
    container_name: ca_org2
    networks:
      - test

  ca_org3:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7254
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17254
    ports:
      - "7254:7254"
      - "17254:17254"
    command: sh -c 'fabric-ca-server start -b admin:admin3 -d'
    volumes:
      - ../organizations/fabric-ca/org3:/etc/hyperledger/fabric-ca-server
    container_name: ca_org3
    networks:
      - test

  ca_org4:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org4
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7354
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17354
    ports:
      - "7354:7354"
      - "17354:17354"
    command: sh -c 'fabric-ca-server start -b admin:admin4 -d'
    volumes:
      - ../organizations/fabric-ca/org4:/etc/hyperledger/fabric-ca-server
    container_name: ca_org4
    networks:
      - test

  ca_org5:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org5
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7454
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17454
    ports:
      - "7454:7454"
      - "17454:17454"
    command: sh -c 'fabric-ca-server start -b admin:admin5 -d'
    volumes:
      - ../organizations/fabric-ca/org5:/etc/hyperledger/fabric-ca-server
    container_name: ca_org5
    networks:
      - test

# The port mappings are:
# 7054:7054 , 17054:17054
# 7154:7154 , 17154:17154
# 7254:7254 , 17254:17254
# 7354:7354 , 17354:17354
# 7454:7454 , 17454:17454
